In [25]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
import pandas as pd

# Adjust the path to your file location in Google Drive
df = pd.read_csv('/co2_emissions_from_agri.csv')
df.head()

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,...,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,...,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,...,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250

In [29]:
print(f'Name of Columns is: \n {df.columns}')

Name of Columns is:
 Index(['Area', 'Year', 'Savanna fires', 'Forest fires', 'Crop Residues',
       'Rice Cultivation', 'Drained organic soils (CO2)',
       'Pesticides Manufacturing', 'Food Transport', 'Forestland',
       'Net Forest conversion', 'Food Household Consumption', 'Food Retail',
       'On-farm Electricity Use', 'Food Packaging',
       'Agrifood Systems Waste Disposal', 'Food Processing',
       'Fertilizers Manufacturing', 'IPPU', 'Manure applied to Soils',
       'Manure left on Pasture', 'Manure Management', 'Fires in organic soils',
       'Fires in humid tropical forests', 'On-farm energy use',
       'Rural population', 'Urban population', 'Total Population - Male',
       'Total Population - Female', 'total_emission',
       'Average Temperature °C'],
      dtype='object')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6965 entries, 0 to 6964
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Area                             6965 non-null   object
 1   Year                             6965 non-null   int64
 2   Savanna fires                    6934 non-null   float64
 3   Forest fires                     6872 non-null   float64
 4   Crop Residues                    5576 non-null   float64
 5   Rice Cultivation                 6965 non-null   float64
 6   Drained organic soils (CO2)      6965 non-null   float64
 7   Pesticides Manufacturing         6965 non-null   float64
 8   Food Transport                   6965 non-null   float64
 9   Forestland                       6472 non-null   float64
 10  Net Forest conversion            6472 non-null   float64
 11  Food Household Consumption       6492 non-null   float64
 12  Food Retail                      6965 non-null   float64
 13  On-farm Electricity Use          6965 non-null   float64
 14  Food Packaging                   6965 non-null   float64
 15  Agrifood Systems Waste Disposal  6965 non-null   float64
 16  Food Processing                  6965 non-null   float64
 17  Fertilizers Manufacturing        6965 non-null   float64
 18  IPPU                             6222 non-null   float64
 19  Manure applied to Soils          6037 non-null   float64
 20  Manure left on Pasture           6965 non-null   float64
 21  Manure Management                6037 non-null   float64
 22  Fires in organic soils           6965 non-null   float64
 23  Fires in humid tropical forests  6810 non-null   float64
 24  On-farm energy use               6009 non-null   float64
 25  Rural population                 6965 non-null   float64
 26  Urban population                 6965 non-null   float64
 27  Total Population - Male          6965 non-null   float64
 28  Total Population - Female        6965 non-null   float64
 29  total_emission                   6965 non-null   float64
 30  Average Temperature °C           6965 non-null   float64
dtypes: float64(29), int64(1), object(1)
memory usage: 1.6+ MB

In [32]:
print(f'Is there missing data in the columns?\n{df.isna().any()}')

Is there missing data in the columns?
Area                               False
Year                               False
Savanna fires                       True
Forest fires                        True
Crop Residues                       True
Rice Cultivation                   False
Drained organic soils (CO2)        False
Pesticides Manufacturing           False
Food Transport                     False
Forestland                          True
Net Forest conversion               True
Food Household Consumption          True
Food Retail                        False
On-farm Electricity Use            False
Food Packaging                     False
Agrifood Systems Waste Disposal    False
Food Processing                    False
Fertilizers Manufacturing          False
IPPU                                True
Manure applied to Soils             True
Manure left on Pasture             False
Manure Management                   True
Fires in organic soils             False
Fires in humid tropical forests     True
On-farm energy use                  True
Rural population                   False
Urban population                   False
Total Population - Male            False
Total Population - Female          False
total_emission                     False
Average Temperature °C             False
dtype: bool

In [38]:
df.isna().sum()

Area                                  0
Year                                  0
Savanna fires                        31
Forest fires                         93
Crop Residues                      1389
Rice Cultivation                      0
Drained organic soils (CO2)           0
Pesticides Manufacturing              0
Food Transport                        0
Forestland                          493
Net Forest conversion               493
Food Household Consumption          473
Food Retail                           0
On-farm Electricity Use               0
Food Packaging                        0
Agrifood Systems Waste Disposal       0
Food Processing                       0
Fertilizers Manufacturing             0
IPPU                                743
Manure applied to Soils             928
Manure left on Pasture                0
Manure Management                   928
Fires in organic soils                0
Fires in humid tropical forests     155
On-farm energy use                  956
Rural population                      0
Urban population                      0
Total Population - Male               0
Total Population - Female             0
total_emission                        0
Average Temperature °C                0
dtype: int64

In [48]:
df.shape

(6965, 31)

In [47]:
# Count rows and columns with missing values
missing_rows = df.isnull().any(axis=1).sum()
missing_columns = df.isnull().sum()
columns_with_missing_values = missing_columns[missing_columns > 0].count()
print(f"\nNumber of rows with missing values: {missing_rows}")
print(f"Number of columns with missing values: {columns_with_missing_values}")

Number of rows with missing values: 2419
Number of columns with missing values: 11

In [49]:
print(f"\nNumber of rows percentantaege: {missing_rows/df.shape[0]*100}")
#print(f"\nNumber of columns percentantaege: {columns_with_missing_values/df.shape[1]*100}")

Number of rows percentantaege: 34.7307968413496

In [54]:
# Separate numeric and non-numeric columns
numeric_df = df.select_dtypes(include=['float64', 'int64'])
non_numeric_df = df.select_dtypes(exclude=['float64', 'int64'])

# Handle missing values using the average for numeric data
numeric_df = numeric_df.fillna(numeric_df.mean())

# Combine the data back
df[numeric_df.columns] = numeric_df


print("\nAfter filling missing values with averages for numeric columns:")
df.head()

After filling missing values with averages for numeric columns:

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,3008.982252,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,3008.982252,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,...,349.1224,0.0,0.0,3008.982252,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,...,352.2947,0.0,0.0,3008.982252,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,...,367.6784,0.0,0.0,3008.982252,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250

In [55]:
# Check again
df.isna().sum()

Area                               0
Year                               0
Savanna fires                      0
Forest fires                       0
Crop Residues                      0
Rice Cultivation                   0
Drained organic soils (CO2)        0
Pesticides Manufacturing           0
Food Transport                     0
Forestland                         0
Net Forest conversion              0
Food Household Consumption         0
Food Retail                        0
On-farm Electricity Use            0
Food Packaging                     0
Agrifood Systems Waste Disposal    0
Food Processing                    0
Fertilizers Manufacturing          0
IPPU                               0
Manure applied to Soils            0
Manure left on Pasture             0
Manure Management                  0
Fires in organic soils             0
Fires in humid tropical forests    0
On-farm energy use                 0
Rural population                   0
Urban population                   0
Total Population - Male            0
Total Population - Female          0
total_emission                     0
Average Temperature °C             0
dtype: int64

In [57]:
print(f'Is there duplicated rows in the columns?\n{df.duplicated().any()}')

Is there duplicated rows in the columns?
False

In [61]:
df_before = df.copy()
df = df[(df['Fertilizers Manufacturing'] - df['Fertilizers Manufacturing'].mean()).abs() <= 3 * df['Fertilizers Manufacturing'].std()]
print("\nAfter removing outliers:")

print("\nNumber of outliers removed:", len(df_before) - len(df))

After removing outliers:

Number of outliers removed: 115

In [62]:
df.head()

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,3008.982252,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,3008.982252,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,...,349.1224,0.0,0.0,3008.982252,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,...,352.2947,0.0,0.0,3008.982252,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,...,367.6784,0.0,0.0,3008.982252,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250

In [63]:
df.shape

(6526, 31)